[bug]
color = "D93F0B"
name = "bug"
description = "直さなければならないバグ"

[design]
color = "6DDD7F"
name = "design"
description = "デザイン周り"

[doc]
color = "4363F2"
name = "doc"
description = "ドキュメント周り"

[enhancement]
color = "2A5D93"
name = "enhancement"
description = "機能周り"

["good first issue"]
color = "9A17EC"
name = "good first issue"
description = "簡単めに取り組める課題"

["help wanted"]
color = "428755"
name = "help wanted"
description = "たすけてー"
